### ISSUE TITLE
Unity SDK dependency problems in package.json and ARCore conflicts

### ISSUE THREAD

**Issue by SinanAkkoyun** [fritzlabs/fritz-unity-sdk#1]
Hello dear Fritz Team!
I really like your project and would love to integrate it into my Unity ARCore application. Sadly, when I try to use the git link in the dependencies Unity Project > Packages > manifest.json it only installs version 1.0.0 (using "ai.fritz.vision": "https://github.com/fritzlabs/fritz-unity-sdk.git#VERSION" throws an error, that nothing under 1.0.3 could be found). Downloading the source code as a ZIP installed me version 1.0.3.
Anyways, doing it one or the other way results in this:

```
An error occurred while resolving packages
Package com.unity.xr.arcore@2. 1. 1 has invalid
dependencies:
com.unity.xr.arsubsystems: Version 2.1.0] is
incompatible with the selected version 2.0.2)
Package com.unity.xr.arkit2. 1. 1 has invalid
dependencies:
com.unity.rarsubsystems: Version [2.1.0] is
incompatible with the selected version 2.0.21
A re-import of the project may be required to fix the
issue or a manual modification of SAnity/AR mobile
- Kople/Packages/manifest.json file.
Click on Retry to relaunch Unity and reopen your
project
Click on Continue to launch Unity. Some or all
packages may not be imported which may cause
compilation errors.
```

So I removed "com.unity.xr.arcore": "2.1.1" and "com.unity.xr.arkit": "2.1.1" from fritz-vision-unity-master > package.json so it doesn't throw this depedency error.

Now the project starts, but there are libraries that are not even included.
The editor throws:
```
fritz-vision-unity-master\Runtime\iOS\Source\FritziOSPoseManager.cs(4,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found
```
for these files:
fritz-vision-unity-master\Runtime\iOS\Source\FritziOSPoseManager.cs(4,7)
fritz-vision-unity-master\Runtime\Unity\FritzPoseManager.cs(4,7)

The Newtonsoft JSON is not being used anywhere, so I removed the include.

It also throws this error:
```
fritz-vision-unity-master\Runtime\Android\FritzAndroidPoseManager.cs(64,47): error CS0246: The type or namespace name 'XRCameraImage' could not be found
```
for these files:
fritz-vision-unity-master\Runtime\Android\FritzAndroidPoseManager.cs(64,47)
fritz-vision-unity-master\Runtime\Unity\FritzPoseManager.cs(95,50)
fritz-vision-unity-master\Runtime\Android\FritzAndroidPoseManager.cs(76,50)
fritz-vision-unity-master\Runtime\Android\FritzAndroidPoseManager.cs(82,49)

I looked into the code and it seems as you use the obsolete (?) XRCameraImage.

So my conclusion is:
- fix the package.json file
- fix the Newtonsoft error
- update the PoseManager files so they use the latest CPU images from the camera of the device (like Google ARCore does) or fix the XRCameraImage implementation

It would be very kind if you look into this. It helps me a lot if you provide a temporary fix for me and later release the fixed version, so I can at least continue working on my stuff.

**Comment by SinanAkkoyun** [comment]
**UPDATE**
Updating the "AR Foundation" in the Unity Package Manager from 2.0.2 to 2.1.4 resolves the XRCameraImage error. But I am asking myself why do I have to update it manually when there is a package.json file.

**Comment by SinanAkkoyun** [comment]
**UPDATE**
Apparently the Newtonsoft JSON library is being used in
fritz-vision-unity-master\Runtime\Unity\FritzPoseManager.cs(107,41).

I am looking into finding the library anywhere, as it is not included automatically.

**Comment by SinanAkkoyun** [comment]
**UPDATE**
According to this resource https://stackoverflow.com/questions/30398407/adding-json-net-to-a-unity3d-project the Unity package for Newtonsoft.JSON can be found here: https://github.com/SaladLab/Json.Net.Unity3D/releases

Just install the .unitypackage file.

**Comment by SinanAkkoyun** [comment]
**UPDATE**
Turns out many of the errors came because I had Google ARCore preconfigured. Now I did everything I documented here again with a clear project.
Now when I try to open the Fritz tab under the Player settings, the page does not build up and following errors occur:
```
Parent directory must exist before creating asset at Assets/Plugins/FritzConfig.asset.
UnityEditor.AssetDatabase:CreateAsset(Object, String)
FritzConfiguration:GetOrCreateSettings() (at C:/Unity/fritz-vision-unity-master/fritz-vision-unity-master/Editor/FritzConfiguration.cs:113)
FritzConfiguration:GetSerializedSettings() (at C:/Unity/fritz-vision-unity-master/fritz-vision-unity-master/Editor/FritzConfiguration.cs:121)
<>c:<CreateFritzConfigProvider>b__5_0(String) (at C:/Unity/fritz-vision-unity-master/fritz-vision-unity-master/Editor/FritzConfiguration.cs:28)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```
```
UnityException: Creating asset at path Assets/Plugins/FritzConfig.asset failed.
UnityEngine.UIElements.UIR.RenderChain.Render (UnityEngine.Rect topRect, UnityEngine.Matrix4x4 projection) (at C:/buildslave/unity/build/Modules/UIElements/Renderer/UIRChainBuilder.cs:238)
UnityEngine.UIElements.UIRRepaintUpdater.DrawChain (UnityEngine.Rect topRect, UnityEngine.Matrix4x4 projection) (at C:/buildslave/unity/build/Modules/UIElements/Renderer/UIRRepaintUpdater.cs:66)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at C:/buildslave/unity/build/Modules/UIElements/Renderer/UIRRepaintUpdater.cs:54)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTree () (at C:/buildslave/unity/build/Modules/UIElements/VisualTreeUpdater.cs:72)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:637)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:240)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:78)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
```

Easy fix, make a "Plugins" folder in the "Assets" directory.

**Comment by SinanAkkoyun** [comment]
**UPDATE**
You don't have to import the Newtonsoft JSON unitypackage if you use an example the Fritz Team provides.

**Comment by SinanAkkoyun** [comment]
To summarize:
It is working for me on a fresh new project. However, it would be awesome if this SDK supported the newest Google ARCore and would not conflict with it.

**Comment by vinegren** [comment]
Wow. That's really interesting! I am trying to make Bird Perch pose detection to work. I have installed json.net from Asset Store and there was an issue in the code of the Fritz package using obsolete methods to PBXProject object. I have just replaced with the new functions in the code (related only to IOS, but I'm building for android) . But this was related to me using 2019.3b version of unity. Latest Arcore and AR foundation, no more errors. 

So all in all I succeeded to see a bird flying innto eternity when in player mode. However when doing an " build and run" , the app is crashing on launch on the phone. I don't know what is the issue, because all "Build Settings /player settings "are set up according to the instructions. 

Is you project running on a phone after doing all that and not using Arcore?

**Comment by vinegren** [comment]
**UPDATE**
I read Android crash logs via ADB and found out that the issue was with the API authorization. I have not registered correctly my pacckage name in the app.fritz.ai. Now when I have added an Android app to my project with the right Package name the app launches.

However I do not see a bird flying to my shoulder when pointing camera in a mirror. Once I saw a bird sitting on a ball in the air on the height of the shoulder. I could not replicate this behaviour on a second app run. I don't know what the issue is..

**Comment by hsiaoer** [comment]
@SinanAkkoyun Thanks for the detailed comments. I'll look into a couple of the issues you've pointed out in the next few days and see if we can improve the package.

@vinegren Does the ball moving at all when a person is in view? I'm wondering if pose predictions are running. Could take a video of what you're seeing?

**Comment by vinegren** [comment]
@hsiaoer thanks for the reply!

I can confirm that it is not moving. The object appears behind me in space, so i see it on one spot if step backwards. 

I have found that there is some issue with reading fritz files responsible for the prediction.  Below is the error log from the phone: 

` **(this appears once i tap the app)** 2019-10-16 15:53:20.912 802-802/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.DefaultCompany.PoseEstimationUnity pid = -1
**(this appears when the feed from camera shows up)** 2019-10-16 15:53:23.539 23113-23130/? E/Unity: AndroidJavaException: java.lang.RuntimeException: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
    java.lang.RuntimeException: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at ai.fritz.customtflite.FritzTFLiteInterpreter.<init>(FritzTFLiteInterpreter.java:48)
        at ai.fritz.customtflite.FritzTFLiteInterpreter.<init>(FritzTFLiteInterpreter.java:39)
        at ai.fritz.vision.base.FritzVisionPredictor.<init>(FritzVisionPredictor.java:38)
        at ai.fritz.vision.poseestimation.FritzVisionPosePredictor.<init>(FritzVisionPosePredictor.java:62)
        at ai.fritz.vision.FritzVision$PoseEstimationFeature.getPredictor(FritzVision.java:155)
        at ai.fritz.visionunity.FritzPoseUnityManager.createPredictor(FritzPoseUnityManager.java:46)
        at ai.fritz.visionunity.FritzPoseUnityManager.buildCPUPredictor(FritzPoseUnityManager.java:62)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
    	at com.unity3d.player.UnityP
**(message when I close the app)** 2019-10-16 15:53:39.484 1351-1551/? E/InputDispatcher: channel '147c955 com.DefaultCompany.PoseEstimationUnity/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
`
I was using Unity 2019.3.0b5 for this and it threw an error when trying to Build. The error was saying that mainTemplate is using old com.android,application and should use com.android.library. When I pressed ok it has generated a new template gradle template. I am installing currently Unity 2019.2.5f1 which you seem to have used.

**Comment by SinanAkkoyun** [comment]
@hsiaoer Thank you. How can I use the Google ARCore image feed with this plugin? I already rewrote some functions in order to better reconstruct the distance the person is away instead of hardcoding it to 2m, but I can not get the latest CPU images from the newest ARCore to get recognized.

**Comment by SinanAkkoyun** [comment]
Hello? My question is still up, why did it got closed??
